baseURL = "https://raul.dev/"
URL = "https://raul.dev/"
languageCode = "en-us"
title = "Raúl Cumplido's Blog"
enableEmoji = true
disableKinds = ["taxonomyTerm", "sitemap", "tags", "categories", "taxonomy", "section"]

[params]
    github = "raulcd"
    linkedin = "raulcumplido"
    twitter = "raulcumplido"
